booking2/config/routes.rb
Rails.application.routes.draw do

  resources :shifts
  resources :calendars
  resources :calendar_groups
  root 'page#home'

  devise_for :users

  resources :admin, only: [:index, :create, :update]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

booking2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

booking2/app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :calendar_group
end

booking2/app/models/calendar_group.rb
class CalendarGroup < ApplicationRecord
end

booking2/app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :calendar
end

booking2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: { standard: 0, admin: 1 }
end

booking2/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @users = User.all
    @user = User.new
  end
end

booking2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

booking2/app/controllers/calendar_groups_controller.rb
class CalendarGroupsController < ApplicationController
  before_action :set_calendar_group, only: %i[ show edit update destroy ]

  # GET /calendar_groups or /calendar_groups.json
  def index
    @calendar_groups = CalendarGroup.all
  end

  # GET /calendar_groups/1 or /calendar_groups/1.json
  def show
  end

  # GET /calendar_groups/new
  def new
    @calendar_group = CalendarGroup.new
  end

  # GET /calendar_groups/1/edit
  def edit
  end

  # POST /calendar_groups or /calendar_groups.json
  def create
    @calendar_group = CalendarGroup.new(calendar_group_params)

    respond_to do |format|
      if @calendar_group.save
        format.html { redirect_to calendar_group_url(@calendar_group), notice: "Calendar group was successfully created." }
        format.json { render :show, status: :created, location: @calendar_group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @calendar_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendar_groups/1 or /calendar_groups/1.json
  def update
    respond_to do |format|
      if @calendar_group.update(calendar_group_params)
        format.html { redirect_to calendar_group_url(@calendar_group), notice: "Calendar group was successfully updated." }
        format.json { render :show, status: :ok, location: @calendar_group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @calendar_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendar_groups/1 or /calendar_groups/1.json
  def destroy
    @calendar_group.destroy!

    respond_to do |format|
      format.html { redirect_to calendar_groups_url, notice: "Calendar group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar_group
      @calendar_group = CalendarGroup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def calendar_group_params
      params.require(:calendar_group).permit(:name, :description)
    end
end

booking2/app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: %i[ show edit update destroy ]

  # GET /calendars or /calendars.json
  def index
    @calendars = Calendar.all
  end

  # GET /calendars/1 or /calendars/1.json
  def show
  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars or /calendars.json
  def create
    @calendar = Calendar.new(calendar_params)

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to calendar_url(@calendar), notice: "Calendar was successfully created." }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1 or /calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to calendar_url(@calendar), notice: "Calendar was successfully updated." }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1 or /calendars/1.json
  def destroy
    @calendar.destroy!

    respond_to do |format|
      format.html { redirect_to calendars_url, notice: "Calendar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def calendar_params
      params.require(:calendar).permit(:name, :description, :calendar_group_id)
    end
end

booking2/app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end
end

booking2/app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: %i[ show edit update destroy ]

  # GET /shifts or /shifts.json
  def index
    @shifts = Shift.all
  end

  # GET /shifts/1 or /shifts/1.json
  def show
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
  end

  # GET /shifts/1/edit
  def edit
  end

  # POST /shifts or /shifts.json
  def create
    @shift = Shift.new(shift_params)

    respond_to do |format|
      if @shift.save
        format.html { redirect_to shift_url(@shift), notice: "Shift was successfully created." }
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shifts/1 or /shifts/1.json
  def update
    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to shift_url(@shift), notice: "Shift was successfully updated." }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1 or /shifts/1.json
  def destroy
    @shift.destroy!

    respond_to do |format|
      format.html { redirect_to shifts_url, notice: "Shift was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shift_params
      params.require(:shift).permit(:name, :description, :calendar_id, :start_time, :duration, :break)
    end
end

booking2/app/helpers/admin_helper.rb
module AdminHelper
end

booking2/app/helpers/application_helper.rb
module ApplicationHelper
end

booking2/app/helpers/calendar_groups_helper.rb
module CalendarGroupsHelper
end

booking2/app/helpers/calendars_helper.rb
module CalendarsHelper
end

booking2/app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

booking2/app/helpers/page_helper.rb
module PageHelper
end

booking2/app/helpers/shifts_helper.rb
module ShiftsHelper
end

booking2/app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

booking2/app/views/calendar_groups/_calendar_group.html.erb
<div id="<%= dom_id calendar_group %>">
  <p>
    <strong>Name:</strong>
    <%= calendar_group.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= calendar_group.description %>
  </p>

</div>

booking2/app/views/calendar_groups/_form.html.erb
<%= form_with(model: calendar_group) do |form| %>
  <% if calendar_group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(calendar_group.errors.count, "error") %> prohibited this calendar_group from being saved:</h2>

      <ul>
        <% calendar_group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

booking2/app/views/calendar_groups/edit.html.erb
<h1>Editing calendar group</h1>

<%= render "form", calendar_group: @calendar_group %>

<br>

<div>
  <%= link_to "Show this calendar group", @calendar_group %> |
  <%= link_to "Back to calendar groups", calendar_groups_path %>
</div>

booking2/app/views/calendar_groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Calendar groups</h1>

<div id="calendar_groups">
  <% @calendar_groups.each do |calendar_group| %>
    <%= render calendar_group %>
    <p>
      <%= link_to "Show this calendar group", calendar_group %>
    </p>
  <% end %>
</div>

<%= link_to "New calendar group", new_calendar_group_path %>

booking2/app/views/calendar_groups/new.html.erb
<h1>New calendar group</h1>

<%= render "form", calendar_group: @calendar_group %>

<br>

<div>
  <%= link_to "Back to calendar groups", calendar_groups_path %>
</div>

booking2/app/views/calendar_groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @calendar_group %>

<div>
  <%= link_to "Edit this calendar group", edit_calendar_group_path(@calendar_group) %> |
  <%= link_to "Back to calendar groups", calendar_groups_path %>

  <%= button_to "Destroy this calendar group", @calendar_group, method: :delete %>
</div>

booking2/app/views/calendars/_calendar.html.erb
<div id="<%= dom_id calendar %>">
  <p>
    <strong>Name:</strong>
    <%= calendar.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= calendar.description %>
  </p>

  <p>
    <strong>Calendar group:</strong>
    <%= calendar.calendar_group_id %>
  </p>

</div>

booking2/app/views/calendars/_form.html.erb
<%= form_with(model: calendar) do |form| %>
  <% if calendar.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
        <% calendar.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :calendar_group_id, style: "display: block" %>
    <%= form.text_field :calendar_group_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

booking2/app/views/calendars/edit.html.erb
<h1>Editing calendar</h1>

<%= render "form", calendar: @calendar %>

<br>

<div>
  <%= link_to "Show this calendar", @calendar %> |
  <%= link_to "Back to calendars", calendars_path %>
</div>

booking2/app/views/calendars/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Calendars</h1>

<div id="calendars">
  <% @calendars.each do |calendar| %>
    <%= render calendar %>
    <p>
      <%= link_to "Show this calendar", calendar %>
    </p>
  <% end %>
</div>

<%= link_to "New calendar", new_calendar_path %>

booking2/app/views/calendars/new.html.erb
<h1>New calendar</h1>

<%= render "form", calendar: @calendar %>

<br>

<div>
  <%= link_to "Back to calendars", calendars_path %>
</div>

booking2/app/views/calendars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @calendar %>

<div>
  <%= link_to "Edit this calendar", edit_calendar_path(@calendar) %> |
  <%= link_to "Back to calendars", calendars_path %>

  <%= button_to "Destroy this calendar", @calendar, method: :delete %>
</div>

booking2/app/views/shifts/_form.html.erb
<%= form_with(model: shift) do |form| %>
  <% if shift.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
        <% shift.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :calendar_id, style: "display: block" %>
    <%= form.text_field :calendar_id %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.datetime_field :start_time %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.text_field :duration %>
  </div>

  <div>
    <%= form.label :break, style: "display: block" %>
    <%= form.text_field :break %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

booking2/app/views/shifts/_shift.html.erb
<div id="<%= dom_id shift %>">
  <p>
    <strong>Name:</strong>
    <%= shift.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= shift.description %>
  </p>

  <p>
    <strong>Calendar:</strong>
    <%= shift.calendar_id %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= shift.start_time %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= shift.duration %>
  </p>

  <p>
    <strong>Break:</strong>
    <%= shift.break %>
  </p>

</div>

booking2/app/views/shifts/edit.html.erb
<h1>Editing shift</h1>

<%= render "form", shift: @shift %>

<br>

<div>
  <%= link_to "Show this shift", @shift %> |
  <%= link_to "Back to shifts", shifts_path %>
</div>

booking2/app/views/shifts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shifts</h1>

<div id="shifts">
  <% @shifts.each do |shift| %>
    <%= render shift %>
    <p>
      <%= link_to "Show this shift", shift %>
    </p>
  <% end %>
</div>

<%= link_to "New shift", new_shift_path %>

booking2/app/views/shifts/new.html.erb
<h1>New shift</h1>

<%= render "form", shift: @shift %>

<br>

<div>
  <%= link_to "Back to shifts", shifts_path %>
</div>

booking2/app/views/shifts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shift %>

<div>
  <%= link_to "Edit this shift", edit_shift_path(@shift) %> |
  <%= link_to "Back to shifts", shifts_path %>

  <%= button_to "Destroy this shift", @shift, method: :delete %>
</div>

booking2/app/views/sidebar/_calendar_group.html.erb
<li>
  <a href="#" class="flex items-center w-full p-2 text-gray-900 transition duration-75 rounded-lg pl-11 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">Invoice</a>
</li>

booking2/app/views/sidebar/_calendar_groups.html.erb
<li>
            <button type="button" class="flex items-center w-full p-2 text-base text-gray-900 transition duration-75 rounded-lg group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700" aria-controls="dropdown-example" data-collapse-toggle="dropdown-example">
                  <%= heroicon "calendar" %>
                  <span class="flex-1 ms-3 text-left rtl:text-right whitespace-nowrap"><%= t("views.calendar_groups") %></span>
                  <%= heroicon "chevron-down" %>
            </button>
            <ul id="dropdown-example" class="hidden py-2 space-y-2">
                  <li>
                     <a href="#" class="flex items-center w-full p-2 text-gray-900 transition duration-75 rounded-lg pl-11 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">1</a>
                  </li>
                  <li>
                     <a href="#" class="flex items-center w-full p-2 text-gray-900 transition duration-75 rounded-lg pl-11 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">2</a>
                  </li>
                  
            </ul>
         </li>

booking2/app/views/sidebar/_index.html.erb
<button data-drawer-target="default-sidebar" data-drawer-toggle="default-sidebar" aria-controls="default-sidebar" type="button" class="inline-flex items-center p-2 mt-2 ms-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
   <span class="sr-only">Open sidebar</span>
   <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
   <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
   </svg>
</button>

<aside id="default-sidebar" class="fixed top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0" aria-label="Sidebar">
   <div class="h-full px-3 py-4 overflow-y-auto bg-gray-50 dark:bg-gray-800">
      <ul class="space-y-2 font-medium">
         <%= render "sidebar/link",
            path: root_path,
            icon: (heroicon "home-modern"),
            text: t("view.home") %>
         <% if user_signed_in? %>
            <%= render "sidebar/link",
               path: admin_index_path,
               icon: (heroicon "wrench-screwdriver"),
               text: t("view.admin") if current_user.admin? %>
            <%= render "sidebar/calendar_groups" %>
            <%= render "sidebar/logout" %>
         <% else %>
            <%= render "sidebar/link", 
               path: new_user_session_path, 
               icon: (heroicon "arrow-right-end-on-rectangle"),
               text: t("view.login") %>
         <% end %>
      </ul>
   </div>
</aside>

booking2/app/views/sidebar/_link.html.erb
<li>
   <a href="<%= path %>" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
      <%= icon %>
      <span class="flex-1 ms-3 whitespace-nowrap"><%= text %></span>
   </a>
</li>

booking2/app/views/sidebar/_logout.html.erb
<li>
   <a href="<%= destroy_user_session_path %>" data-turbo-method="delete" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
      <%= heroicon "arrow-right-start-on-rectangle" %>
      <span class="flex-1 ms-3 whitespace-nowrap"><%= t("view.logout") %></span>
   </a>
</li>